name: HPA

on:
    push:
        paths:
            - 'deploy/hpa/**'
            - '.github/workflows/hpa.yml'
        branches:
            - main

jobs:
    deployDev:
        name: Deploy HPA to dev
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: dev-gcp
                  RESOURCE: deploy/hpa/hpa.yml
                  VARS: deploy/hpa/dev-hpa.yml

    deployProd:
        name: Deploy HPA to prod
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: nais/deploy/actions/deploy@v2
              env:
                  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                  CLUSTER: prod-gcp
                  RESOURCE: deploy/hpa/hpa.yml
                  VARS: deploy/hpa/prod-hpa.yml
